dubbo:
  protocol: 
   port: -1
   name: dubbo
  application: 
   name: urlInterceptor-server-app
  registry:
   address: zookeeper://127.0.0.1:2181
   timeout: 30000
  packageName: com.tdh.urlInterceptor.service.impl
  
mongodb:
    address: 127.0.0.1:27017
    username: gps
    password: gps
    database: test
    authenticationDatabase: test
    connectionsPerHost: 100
    connectTimeout: 60000
    maxWaitTime: 120000
    maxConnectionIdleTime: 600000
    threadsAllowedToBlockForConnectionMultiplier: 50
    socketTimeout: 30000
    minConnectionsPerHost: 10
    
server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.169:3306/gps_tuning?useUnicode=true&amp;characterEncoding=UTF-8
        username: ifm
        password: ifm
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            connectionTimeout: 60000
            validationTimeout: 5000
            idleTimeout: 600000
            maxLifetime: 1800000
            minimumIdle: 10
            maximumPoolSize: 100
            connectionInitSql: select 1
            autoCommit: true
    redis:
        host: 192.168.1.204
        password: 
        port: 6379
        timeout: 10000
        pool:
         max-active: 100
         max-idle: 10
         min-idle: 1
         max-wait: 30000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.tdh.urlInterceptor.model

  