spring:
  application:
    name: urlInterceptor-register9502
#  profiles: eureka-server-9502
server:
  port: 9502
eureka:
  instance:
    hostname: eureka-server-9502
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9501/eureka/,http://localhost:9500/eureka/