spring:
  application:
    name: urlInterceptor-consumer
server:
  port: 9600

eureka:
  instance:
    prefer-ip-address: true 
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka/,http://localhost:9501/eureka/,http://localhost:9502/eureka/

feign:
 hystrix:
  enabled: true
  
ribbon:
# 设置连接超时时间
 ConnectTimeout: 5000
# 设置读取超时时间
 ReadTimeout: 5000
# 对所有操作请求都进行重试
 OkToRetryOnAllOperations: true
# 切换实例的重试次数
 MaxAutoRetriesNextServer: 2
# 对当前实例的重试次数
 MaxAutoRetries: 1
 
# 设置熔断超时时间
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 5000
# 开启熔断功能
    timeout:
     enabled: true
      